# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\uiMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(517, 458)
        MainWindow.setMinimumSize(QtCore.QSize(517, 458))
        MainWindow.setMaximumSize(QtCore.QSize(517, 458))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-1, 0, 521, 461))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_contacts = QtWidgets.QWidget()
        self.tab_contacts.setObjectName("tab_contacts")
        self.contacts_input_entreprise = QtWidgets.QLineEdit(self.tab_contacts)
        self.contacts_input_entreprise.setGeometry(QtCore.QRect(10, 70, 231, 31))
        self.contacts_input_entreprise.setObjectName("contacts_input_entreprise")
        self.contacts_input_contact = QtWidgets.QLineEdit(self.tab_contacts)
        self.contacts_input_contact.setGeometry(QtCore.QRect(330, 70, 171, 31))
        self.contacts_input_contact.setObjectName("contacts_input_contact")
        self.contacts_input_telephone = QtWidgets.QLineEdit(self.tab_contacts)
        self.contacts_input_telephone.setGeometry(QtCore.QRect(10, 130, 231, 31))
        self.contacts_input_telephone.setObjectName("contacts_input_telephone")
        self.contacts_input_mail = QtWidgets.QLineEdit(self.tab_contacts)
        self.contacts_input_mail.setGeometry(QtCore.QRect(10, 190, 231, 31))
        self.contacts_input_mail.setObjectName("contacts_input_mail")
        self.contacts_label_entreprise = QtWidgets.QLabel(self.tab_contacts)
        self.contacts_label_entreprise.setGeometry(QtCore.QRect(10, 50, 231, 21))
        self.contacts_label_entreprise.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_label_entreprise.setObjectName("contacts_label_entreprise")
        self.contacts_label_contact = QtWidgets.QLabel(self.tab_contacts)
        self.contacts_label_contact.setGeometry(QtCore.QRect(270, 50, 231, 21))
        self.contacts_label_contact.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_label_contact.setObjectName("contacts_label_contact")
        self.contacts_label_telephone = QtWidgets.QLabel(self.tab_contacts)
        self.contacts_label_telephone.setGeometry(QtCore.QRect(10, 110, 231, 21))
        self.contacts_label_telephone.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_label_telephone.setObjectName("contacts_label_telephone")
        self.contacts_label_adresse = QtWidgets.QLabel(self.tab_contacts)
        self.contacts_label_adresse.setGeometry(QtCore.QRect(270, 110, 231, 21))
        self.contacts_label_adresse.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_label_adresse.setObjectName("contacts_label_adresse")
        self.contacts_label_mail = QtWidgets.QLabel(self.tab_contacts)
        self.contacts_label_mail.setGeometry(QtCore.QRect(10, 170, 231, 21))
        self.contacts_label_mail.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_label_mail.setObjectName("contacts_label_mail")
        self.contacts_textEdit_adresse = QtWidgets.QPlainTextEdit(self.tab_contacts)
        self.contacts_textEdit_adresse.setGeometry(QtCore.QRect(270, 130, 231, 91))
        self.contacts_textEdit_adresse.setObjectName("contacts_textEdit_adresse")
        self.contacts_btn_save = QtWidgets.QPushButton(self.tab_contacts)
        self.contacts_btn_save.setGeometry(QtCore.QRect(10, 390, 231, 31))
        self.contacts_btn_save.setObjectName("contacts_btn_save")
        self.contacts_combobox_sexe = QtWidgets.QComboBox(self.tab_contacts)
        self.contacts_combobox_sexe.setGeometry(QtCore.QRect(270, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.contacts_combobox_sexe.setFont(font)
        self.contacts_combobox_sexe.setObjectName("contacts_combobox_sexe")
        self.contacts_combobox_sexe.addItem("")
        self.contacts_combobox_sexe.addItem("")
        self.contacts_btn_listes = QtWidgets.QPushButton(self.tab_contacts)
        self.contacts_btn_listes.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.contacts_btn_listes.setObjectName("contacts_btn_listes")
        self.contacts_btn_nouveau = QtWidgets.QPushButton(self.tab_contacts)
        self.contacts_btn_nouveau.setGeometry(QtCore.QRect(270, 10, 231, 31))
        self.contacts_btn_nouveau.setObjectName("contacts_btn_nouveau")
        self.contacts_btn_supprimer = QtWidgets.QPushButton(self.tab_contacts)
        self.contacts_btn_supprimer.setGeometry(QtCore.QRect(270, 390, 231, 31))
        self.contacts_btn_supprimer.setObjectName("contacts_btn_supprimer")
        self.frame = QtWidgets.QFrame(self.tab_contacts)
        self.frame.setGeometry(QtCore.QRect(20, 280, 471, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.contacts_btn_generer = QtWidgets.QPushButton(self.frame)
        self.contacts_btn_generer.setGeometry(QtCore.QRect(250, 10, 211, 31))
        self.contacts_btn_generer.setObjectName("contacts_btn_generer")
        self.contacts_checkbox_cv = QtWidgets.QCheckBox(self.frame)
        self.contacts_checkbox_cv.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.contacts_checkbox_cv.setObjectName("contacts_checkbox_cv")
        self.contacts_checkbox_lm = QtWidgets.QCheckBox(self.frame)
        self.contacts_checkbox_lm.setGeometry(QtCore.QRect(20, 50, 171, 31))
        self.contacts_checkbox_lm.setObjectName("contacts_checkbox_lm")
        self.contacts_btn_visualiser = QtWidgets.QPushButton(self.frame)
        self.contacts_btn_visualiser.setGeometry(QtCore.QRect(250, 50, 211, 31))
        self.contacts_btn_visualiser.setObjectName("contacts_btn_visualiser")
        self.frame.raise_()
        self.contacts_input_entreprise.raise_()
        self.contacts_input_contact.raise_()
        self.contacts_input_telephone.raise_()
        self.contacts_input_mail.raise_()
        self.contacts_label_entreprise.raise_()
        self.contacts_label_contact.raise_()
        self.contacts_label_telephone.raise_()
        self.contacts_label_adresse.raise_()
        self.contacts_label_mail.raise_()
        self.contacts_textEdit_adresse.raise_()
        self.contacts_btn_save.raise_()
        self.contacts_combobox_sexe.raise_()
        self.contacts_btn_listes.raise_()
        self.contacts_btn_nouveau.raise_()
        self.contacts_btn_supprimer.raise_()
        self.tabWidget.addTab(self.tab_contacts, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.tabWidget.addTab(self.tab_config, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLocalisation_Images = QtWidgets.QAction(MainWindow)
        self.actionLocalisation_Images.setObjectName("actionLocalisation_Images")
        self.actionConnexion_MYSQL = QtWidgets.QAction(MainWindow)
        self.actionConnexion_MYSQL.setObjectName("actionConnexion_MYSQL")
        self.actionConnexion_ACCESS = QtWidgets.QAction(MainWindow)
        self.actionConnexion_ACCESS.setObjectName("actionConnexion_ACCESS")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python - pyMailing"))
        self.contacts_label_entreprise.setText(_translate("MainWindow", "ENTREPRISE"))
        self.contacts_label_contact.setText(_translate("MainWindow", "CONTACT"))
        self.contacts_label_telephone.setText(_translate("MainWindow", "TELEPHONE"))
        self.contacts_label_adresse.setText(_translate("MainWindow", "ADRESSE"))
        self.contacts_label_mail.setText(_translate("MainWindow", "MAIL"))
        self.contacts_btn_save.setText(_translate("MainWindow", "SAUVEGARDER"))
        self.contacts_combobox_sexe.setItemText(0, _translate("MainWindow", "Mme"))
        self.contacts_combobox_sexe.setItemText(1, _translate("MainWindow", "M"))
        self.contacts_btn_listes.setText(_translate("MainWindow", "LISTES"))
        self.contacts_btn_nouveau.setText(_translate("MainWindow", "NOUVEAU"))
        self.contacts_btn_supprimer.setText(_translate("MainWindow", "SUPPRIMER"))
        self.contacts_btn_generer.setText(_translate("MainWindow", "GENERER"))
        self.contacts_checkbox_cv.setText(_translate("MainWindow", "CURICULUM VITAE"))
        self.contacts_checkbox_lm.setText(_translate("MainWindow", "LETTRE MOTIVATION"))
        self.contacts_btn_visualiser.setText(_translate("MainWindow", "VISUALISER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_contacts), _translate("MainWindow", "CONTACTS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("MainWindow", "CONFIG"))
        self.actionLocalisation_Images.setText(_translate("MainWindow", "Localisation Images"))
        self.actionConnexion_MYSQL.setText(_translate("MainWindow", "Connexion MYSQL"))
        self.actionConnexion_ACCESS.setText(_translate("MainWindow", "Connexion ACCESS"))
        self.actionAbout.setText(_translate("MainWindow", "?"))
